trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  GOPATH: '$(Agent.HomeDirectory)/go' # Go workspace path
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/opt/hostedtoolcache/go/1.15.8/x64' # Go installation path
  DARWIN_AMD64_BINARY: "gitleaks-darwin-amd64"
  LINUX_AMD64_BINARY: "gitleaks-linux-amd64"
  WIN_AMD64_BINARY: "gitleaks-win-amd64.exe"
  BUILD_ID: ${Build.BuildNumber}

steps:
- task: CmdLine@2
  inputs:
    script: |
      env GOOS="darwin" GOARCH="amd64" go build -o "build/${DARWIN_AMD64_BINARY}" -ldflags "-X=github.com/zricethezav/gitleaks/v7/version.Version=${BUILD_ID}"